### ISSUE TITLE
绘制图形会使得Jupyter Notebook页面布局出现混乱【linear-regression-scratch.ipynb】

### ISSUE THREAD

**Issue by panovr** [sangyx/d2l-torch#5]
在【linear-regression-scratch.ipynb】中运行以下代码：
```
def use_svg_display():
    # 用矢量图显示
    display.set_matplotlib_formats('svg')

def set_figsize(figsize=(3.5, 2.5)):
    use_svg_display()
    # 设置图的尺寸
    plt.rcParams['figure.figsize'] = figsize

set_figsize()
plt.scatter(features[:, 1].numpy(), labels.numpy(), 1); # 加分号只显示图
```

会使得Jupyter Notebook的页面布局出现混乱。

**Comment by panovr** [comment]
![d2l](https://user-images.githubusercontent.com/319796/68990891-974f6900-0893-11ea-94f8-4378c4847c3a.png)

**Comment by sangyx** [comment]
你好，请问能否提供一下您使用的环境和matplotlib版本，我使用matplotlib==2.2.2在jupyter lab中没有复现这个问题

**Comment by panovr** [comment]
我的环境是conda，matplotlib==3.1.0

**Comment by sangyx** [comment]
matplotlib版本较高会出现这一问题，可以通过降低matplotlib版本来解决：`conda install matplotlib==2.2.2`
